<!DOCTYPE html><html lang="ru"><head><link rel="stylesheet" type="text/css" href="media/style/[+theme+]/style.css"><link rel="stylesheet" type="text/css" href="[+module_theme+]css/main.css[+rand+]"><script src="[+module_theme+]js/jquery.js"></script><script type="text/javascript" src="media/script/mootools/mootools.js"></script><script type="text/javascript" src="media/script/mootools/moodx.js"></script><script type="text/javascript" src="media/script/tabpane.js"></script><script type="text/javascript" src="media/script/datefunctions.js"></script><script type="text/javascript" src="media/calendar/datepicker.js"></script></head><body><div id="actions"><ul class="actionButtons"><li id="Button2"><a href="javascript:;" class="primary" onclick="document.location.href='index.php?a=112&id=[+module_id+]&action=1';"><img src="media/style/[+theme+]/images/icons/add.png">&nbsp;[+module_add_gallery+]</a></li><li id="Button1"><a href="javascript:;" onclick="closeModule();"><img src="media/style/[+theme+]/images/icons/stop.png">&nbsp;[+module_close+]</a></li></ul></div><h1 class="evocontentgallery__modulename">[+ioweb+] [+module_evocontentgallery_name+]</h1><div class="sectionBody"><div class="tab-pane" id="modulePane"><script type="text/javascript">window.tp = new WebFXTabPane( document.getElementById( "modulePane"), true);</script><div class="tab-page" id="tabModule_0"><h2 class="tab">[+module_galleries_list+]</h2><script type="text/javascript">window.tp.addTabPage( document.getElementById( "tabModule_0" ) );</script><table border="0" cellspacing="0" cellpadding="1" class="sortabletable"><tr><th>[+module_gallery_id+]</th><th>[+module_gallery+]</th><th>[+module_gallery_sort+]</th><th>[+module_gallery_images_count+]</th><th>[+module_state_published+]</th><th>[+module_action+]</th></tr><tbody id="sortableTable">[+row.galleries+]</tbody></table><div></div></div></div></div>[+debug_info+] [+footer+]<script type="text/javascript">var jq = jQuery.noConflict(),
				closeModule = function(){
					a = jq("#site > a", window.parent.frames[0].document);
					a.trigger('click');
					a.parent().trigger('click');
					document.location.href='index.php?a=2';	
				};
			jq(function(){
				
			});</script></body></html>